# Try seurat on breast cancer data

ref: https://satijalab.org/seurat/articles/pbmc3k_tutorial


```{r}
library(Seurat)
```


```{r}
# load data
data <- Read10X_h5("/group/ag_nowick/data/yao/CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma_filtered_feature_bc_matrix.h5")

# create seurat object
# at least three cells need to express this gene
# at least 200 genes need to be expressed in a cell
sobj <- CreateSeuratObject(counts=data, project="bc",
                           min.cells=3, min.features=200)

# store mitochondria information
sobj[["percent.mt"]] <- PercentageFeatureSet(sobj, pattern="^MT-")
```

Use FeatureScatter to see feature-feature relationship
```{r}
plot1 <- FeatureScatter(sobj, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(sobj, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2
```
```{r}
# based on feature plot we subset the data
sobj <- subset(sobj, subset = nFeature_RNA > 200 & nFeature_RNA < 11000 & percent.mt < 4)

# normalized data
sobj <- NormalizeData(sobj, normalization.method = "LogNormalize", scale.factor = 10000)
```

Identification of highly variable features (feature selection)
```{r}
sobj <- FindVariableFeatures(sobj, selection.method = "vst", nfeatures=2000)
top10 <-head(VariableFeatures(sobj), 10) 
plot1 <- VariableFeaturePlot(sobj)
plot2 <- LabelPoints(plot = plot1, points = top10, repel=TRUE)
plot2
```
```{r}
all.genes <- rownames(sobj)
sobj <- ScaleData(sobj, features = all.genes) # can consider SCTransform
```

```{r}
sobj <- RunPCA(sobj, features=VariableFeatures(object=sobj))
VizDimLoadings(sobj, dims=1:2, reduction="pca")
```

Cluster the cells
```{r}
sobj <- FindNeighbors(sobj, dims=1:10)
sobj <- FindClusters(sobj, resolution=0.5)
```

## Run non-linear dimensional reduction
```{r}
sobj <- RunUMAP(sobj, dims=1:10)
DimPlot(sobj, reduction="umap")
```


